
02/02/2024 21:17:03 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
/home/ubuntu/miniconda3/envs/chatglm2/lib/python3.10/site-packages/datasets/load.py:2483: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
[INFO|configuration_utils.py:667] 2024-02-02 21:17:04,780 >> loading configuration file /data/ai/model/chatglm2-6b/config.json
[INFO|configuration_utils.py:667] 2024-02-02 21:17:04,782 >> loading configuration file /data/ai/model/chatglm2-6b/config.json
[INFO|configuration_utils.py:725] 2024-02-02 21:17:04,783 >> Model config ChatGLMConfig {
  "_name_or_path": "/data/ai/model/chatglm2-6b",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1e-05,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_layers": 28,
  "original_rope": true,
  "pad_token_id": 0,
  "padded_vocab_size": 65024,
  "post_layer_norm": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "rmsnorm": true,
  "seq_length": 32768,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.30.2",
  "use_cache": true,
  "vocab_size": 65024
}
[INFO|tokenization_utils_base.py:1821] 2024-02-02 21:17:04,784 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1821] 2024-02-02 21:17:04,784 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1821] 2024-02-02 21:17:04,784 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1821] 2024-02-02 21:17:04,784 >> loading file tokenizer_config.json
[INFO|modeling_utils.py:2575] 2024-02-02 21:17:04,827 >> loading weights file /data/ai/model/chatglm2-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:577] 2024-02-02 21:17:04,828 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.30.2"
}

Loading checkpoint shards:  57%|█████████████████████████████████████████████████████▋                                        | 4/7 [00:03<00:02,  1.34it/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.42it/s]
[INFO|modeling_utils.py:3295] 2024-02-02 21:17:09,784 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.
[WARNING|modeling_utils.py:3297] 2024-02-02 21:17:09,784 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data/ai/model/chatglm2-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2927] 2024-02-02 21:17:09,785 >> Generation config file not found, using a generation config created from the model config.
prefix:
Traceback (most recent call last):
  File "/data/ai/ChatGLM2-6B/ptuning/main.py", line 483, in <module>
    main()
  File "/data/ai/ChatGLM2-6B/ptuning/main.py", line 271, in main
    print("eval dataset:" + eval_dataset)
TypeError: can only concatenate str (not "Dataset") to str
Traceback (most recent call last):
  File "/data/ai/ChatGLM2-6B/ptuning/main.py", line 483, in <module>
    main()
  File "/data/ai/ChatGLM2-6B/ptuning/main.py", line 271, in main
    print("eval dataset:" + eval_dataset)
TypeError: can only concatenate str (not "Dataset") to str